### ISSUE TITLE
ImportError: cannot import name '_new_empty_tensor' from 'torchvision.ops' 

### ISSUE THREAD

**Issue by cristophersfr** [mlpc-ucsd/LETR#2]
Hi guys, 

I'm trying to run: `bash script/train/a0_train_stage1_res50.sh  res50_stage1`

But unfortunately, I'm getting the following error: 

```
Traceback (most recent call last):
  File "/home/cristopher/Workspace/LETR/src/main.py", line 13, in <module>
    import datasets
  File "/home/cristopher/Workspace/LETR/src/datasets/__init__.py", line 5, in <module>
    from .coco import build as build_coco
  File "/home/cristopher/Workspace/LETR/src/datasets/coco.py", line 10, in <module>
    import datasets.transforms as T
  File "/home/cristopher/Workspace/LETR/src/datasets/transforms.py", line 18, in <module>
    from util.misc import interpolate
  File "/home/cristopher/Workspace/LETR/src/util/misc.py", line 22, in <module>
    from torchvision.ops import _new_empty_tensor
ImportError: cannot import name '_new_empty_tensor' from 'torchvision.ops' (/home/cristopher/miniconda3/envs/letr/lib/python3.9/site-packages/torchvision/ops/__init__.py)
Traceback (most recent call last):
  File "/home/cristopher/Workspace/LETR/src/main.py", line 13, in <module>
    import datasets
  File "/home/cristopher/Workspace/LETR/src/datasets/__init__.py", line 5, in <module>
    from .coco import build as build_coco
  File "/home/cristopher/Workspace/LETR/src/datasets/coco.py", line 10, in <module>
    import datasets.transforms as T
  File "/home/cristopher/Workspace/LETR/src/datasets/transforms.py", line 18, in <module>
    from util.misc import interpolate
  File "/home/cristopher/Workspace/LETR/src/util/misc.py", line 22, in <module>
    from torchvision.ops import _new_empty_tensor
ImportError: cannot import name '_new_empty_tensor' from 'torchvision.ops' (/home/cristopher/miniconda3/envs/letr/lib/python3.9/site-packages/torchvision/ops/__init__.py)
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/cristopher/Workspace/LETR/src/main.py", line 13, in <module>
  File "/home/cristopher/Workspace/LETR/src/main.py", line 13, in <module>
        import datasetsimport datasets

  File "/home/cristopher/Workspace/LETR/src/datasets/__init__.py", line 5, in <module>
  File "/home/cristopher/Workspace/LETR/src/datasets/__init__.py", line 5, in <module>
        from .coco import build as build_cocofrom .coco import build as build_coco

  File "/home/cristopher/Workspace/LETR/src/datasets/coco.py", line 10, in <module>
  File "/home/cristopher/Workspace/LETR/src/datasets/coco.py", line 10, in <module>
        import datasets.transforms as Timport datasets.transforms as T

  File "/home/cristopher/Workspace/LETR/src/datasets/transforms.py", line 18, in <module>
  File "/home/cristopher/Workspace/LETR/src/datasets/transforms.py", line 18, in <module>
        from util.misc import interpolatefrom util.misc import interpolate

  File "/home/cristopher/Workspace/LETR/src/util/misc.py", line 22, in <module>
  File "/home/cristopher/Workspace/LETR/src/util/misc.py", line 22, in <module>
        from torchvision.ops import _new_empty_tensorfrom torchvision.ops import _new_empty_tensor

ImportErrorImportError: : cannot import name '_new_empty_tensor' from 'torchvision.ops' (/home/cristopher/miniconda3/envs/letr/lib/python3.9/site-packages/torchvision/ops/__init__.py)cannot import name '_new_empty_tensor' from 'torchvision.ops' (/home/cristopher/miniconda3/envs/letr/lib/python3.9/site-packages/torchvision/ops/__init__.py)
```

My setup has the following packages: 
```
pytorch                   1.9.0           py3.9_cuda10.2_cudnn7.6.5_0    pytorch
torchvision               0.10.0                   pypi_0    pypi
```

I tried finding what was the actual problem, and had failed so far.

**Comment by adakoda** [comment]
This version of the combination worked.
- python: 3.7.10
- pytorch: 1.8.0+cu111
- torchvision: 0.9.0+cu11

If you are working on Colab, you can downgrade with the following command.

```
!pip install torch==1.8.0+cu111 torchvision==0.9.0+cu111 -f https://download.pytorch.org/whl/torch_stable.html
```

And then, I realized. At least, the following lines have a bug that judges torchvision version as 0.1 when it is 0.10.
https://github.com/mlpc-ucsd/LETR/blob/master/src/util/misc.py#L21
```
if float(torchvision.__version__[:3]) < 0.7:
```

**Comment by cristophersfr** [comment]
Thank you for your input. This is the behavior for version '0.10'. A simple tweak solved it, but a lot of other problems emerged. I'll try addressing this myself, and then, maybe, returning a PR. 

```python3
if float(torchvision.__version__[:3]) < 0.7:
```
returns
```python
'0.1'
```
